// ==========================================
// THIS FILE IS AUTO-GENERATED BY A SCRIPT.
// DO NOT EDIT THIS FILE MANUALLY.
// ==========================================

import classesMap from './rulebook/classes.json';
import backgroundsMap from './rulebook/backgrounds.json';
import class_monksubclasses from './rulebook/classes/monk-subclasses.json';
import class_monk from './rulebook/classes/monk.json';
import feat_lucky from './rulebook/feats/lucky.json';

export { classesMap, backgroundsMap };

export const classRegistry: Record<string, any> = {
    "monk": class_monk,
};

export const subclassRegistry: Record<string, any> = {
    "monk-subclasses": class_monksubclasses,
};

export const featRegistry: Record<string, any> = {
    "lucky": feat_lucky,
};
